import React, { useState, useEffect, FormEvent, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { doc, getDoc, onSnapshot, collection, setDoc, updateDoc, deleteDoc, query, getDocs, writeBatch } from 'firebase/firestore';
import { db, initAuth, googleSignIn, getAccessToken, logout } from './firebase';
import {
  Calendar,
  Users,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Download,
  LogOut,
  Clock,
  ClipboardList,
  Shield,
  FileText,
  UserCheck,
  User as UserIcon,
  RefreshCw,
  PlusCircle,
  ArrowRight,
  Info,
  ChevronRight,
  UserPlus,
  Upload,
  Coffee,
  Utensils,
  Printer,
  Search,
  MessageSquare,
  MessageCircle,
  HelpCircle,
  Send,
  ImageIcon,
  Link,
  Trash2,
  Paperclip,
  ExternalLink,
  Bell,
  Activity,
  PieChart,
  BarChart2,
  GitPullRequest,
  LayoutDashboard,
  Wallet,
  PhoneCall,
  History,
  ShieldCheck,
  FileSpreadsheet,
  Copy,
  Lock,
  Sparkles,
  Sun,
  Cloudy,
  Cloud,
  Phone,
  Mail,
  X,
} from 'lucide-react';
import { Toaster, toast } from 'sonner';
import { AIChatWidget } from './AIChatWidget';
import { MessagingSystem } from './components/MessagingSystem';
import { DataVault } from './components/DataVault';
import { IntegrationsManager } from './components/IntegrationsManager';
import { ScreenshotUpload } from './components/ScreenshotUpload';
import { DashboardSummary } from './components/DashboardSummary';
import { QAScorecards } from './components/QAScorecards';
import { PatientSearchHub } from './components/PatientSearchHub';
import { AnnouncementsTab } from './components/AnnouncementsTab';
import * as XLSX from 'xlsx';
import {
  isTLName,
  isQAName,
  capitalizeName,
  getStorageItem,
  setStorageItem,
  validateSwapRequest,
  validateAnnualRequest,
  getInitialRequests,
  generateCSV,
  generateTextReport,
  formatDateNice,
  getInitialSchedules,
  parseScheduleCSV,
  parseAgentDirectoryCSV,
  generateScheduleTemplateFile,
  getAgentLOB,
  getAgentTL,
  getAgentMeta,
  generateInquiriesCSV,
  generateTimeLogsCSV,
  formatAgentName,
  generateFintechRequestsCSV,
  generateFintechComplaintsCSV,
  generateClientCommsCSV,
  generateCasesCSV,
  generateSchedulesCSV,
  getLocalISOString,
  getLocalTimeZone,
  normalizeName,
